(function() {
  'use strict';

  const t = (k, vars) => window.LeakdI18n ? window.LeakdI18n.t(k, vars) : k;

  function generatePDF(subs, totals) {
    if (window.LeakdPro && !window.LeakdPro.isPro()) {
      if (typeof openProModal === 'function') openProModal();
      return;
    }

    const lang = window.LeakdI18n ? window.LeakdI18n.lang : 'en';
    const activeList = subs.filter(s => !s.paused);
    
    // Create print window
    const win = window.open('', '_blank');
    if (!win) {
      alert(t('toast.popupBlocked') || 'Please allow popups to print the report.');
      return;
    }

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>Leakd - Accountant Report</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #111; margin: 40px; }
          h1 { font-size: 24px; margin-bottom: 5px; }
          .header { border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
          .meta { font-size: 12px; color: #555; }
          
          .summary { display: flex; gap: 40px; margin-bottom: 40px; }
          .summary-box { background: #f5f5f5; padding: 15px 20px; border-radius: 8px; min-width: 150px; }
          .summary-label { font-size: 11px; text-transform: uppercase; color: #666; margin-bottom: 5px; font-weight: bold; }
          .summary-val { font-size: 24px; font-weight: bold; }
          
          table { width: 100%; border-collapse: collapse; margin-bottom: 40px; font-size: 13px; }
          th { text-align: left; padding: 10px; border-bottom: 1px solid #000; font-weight: bold; }
          td { padding: 10px; border-bottom: 1px solid #ddd; }
          .price-col { text-align: right; }
          
          .footer { margin-top: 50px; text-align: center; font-size: 10px; color: #888; border-top: 1px solid #ddd; padding-top: 20px; }
          
          @media print {
            body { margin: 0; }
            button { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Subscription Report</h1>
          <div class="meta">Generated by Leakd on ${new Date().toLocaleDateString(lang)}</div>
        </div>
        
        <div class="summary">
          <div class="summary-box">
            <div class="summary-label">Monthly Total</div>
            <div class="summary-val">${formatPrice(totals.monthly)}</div>
          </div>
          <div class="summary-box">
            <div class="summary-label">Yearly Total</div>
            <div class="summary-val">${formatPrice(totals.yearly)}</div>
          </div>
          <div class="summary-box">
            <div class="summary-label">Active Subscriptions</div>
            <div class="summary-val">${activeList.length}</div>
          </div>
        </div>
        
        <table>
          <thead>
            <tr>
              <th>Service</th>
              <th>Category</th>
              <th>Billing Cycle</th>
              <th class="price-col">Amount</th>
            </tr>
          </thead>
          <tbody>
            ${activeList.map(s => {
              const cycleLabel = t('cycle.' + (s.cycle === 'monthly' ? 'mo' : s.cycle === 'yearly' ? 'yr' : 'wk')).replace('/','');
              const cat = window.LeakdI18n ? window.LeakdI18n.t('cat.' + s.category) : s.category;
              return `
                <tr>
                  <td><strong>${s.name}</strong></td>
                  <td>${cat || s.category}</td>
                  <td>${cycleLabel}</td>
                  <td class="price-col">${formatPrice(s.price, s.currency)}</td>
                </tr>
              `;
            }).join('')}
          </tbody>
        </table>
        
        <div class="footer">
          Generated automatically by Leakd App (leakd.app)
        </div>
        
        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
      </html>
    `;

    win.document.open();
    win.document.write(html);
    win.document.close();
  }

  function formatPrice(amount, code) {
    const settings = window.LeakdState || {};
    const target = code || settings.currencyCode || 'USD';
    if (window.LeakdLocale) return window.LeakdLocale.formatMoney(amount, target);
    if (window.LeakdCurrency) {
      const s = window.LeakdCurrency.getSymbol(target);
      if (target === 'HUF' || s === 'Ft') return Math.round(amount).toLocaleString() + ' Ft';
      if (s === '¥') return s + Math.round(amount).toLocaleString();
      return s + Number(amount).toFixed(2);
    }
    return (settings.currency || '$') + Number(amount).toFixed(2);
  }

  window.LeakdPdf = { generate: generatePDF };

})();
