const fs = require('fs');
const path = 'c:/Users/local_user/Documents/leakd/leakd/js/i18n.js';
let content = fs.readFileSync(path, 'utf8');

// Fix English block first (manually fix PANIKGOMB)
content = content.replace("'panic.button': 'PANIKGOMB',", "'panic.button': 'PANIC BUTTON',");

const allLangs = {
    'pl': {
        'menu.activity': 'Dziennik aktywności',
        'menu.activitySub': 'Zobacz każdą wprowadzoną zmianę',
        'activity.title': 'Dziennik aktywności',
        'activity.empty': 'Brak aktywności. Dodaj subskrypcję, aby zacząć.',
        'activity.added': 'Dodano {name}',
        'activity.edited': 'Edytowano {name}',
        'activity.cancelled': 'Anulowano {name}',
        'activity.paused': 'Wstrzymano {name}',
        'activity.resumed': 'Wznowiono {name}',
        'activity.restored': 'Przywrócono {name}',
        'activity.deleted': 'Usunięto {name}',
        'activity.imported': 'Zaimportowano {n} subskrypcji',
        'personality.title': 'Twoja osobowość subskrypcyjna',
        'personality.quietCutter': 'Cichy Wycinacz',
        'personality.quietCutterTag': 'Anulowałeś kilka subskrypcji w tym roku — ciche zwycięstwo',
        'personality.bundleMaster': 'Mistrz Pakietów',
        'personality.bundleMasterTag': 'Wiesz, jak kumulować oszczędności',
        'personality.streamingJunkie': 'Uzależniony od Streamingu',
        'personality.streamingJunkieTag': '3+ subskrypcje rozrywkowe — kochasz swoje seriale',
        'personality.aiHoarder': 'Gromadzący AI',
        'personality.aiHoarderTag': 'Zbierasz narzędzia AI szybciej, niż one wypuszczają aktualizacje',
        'personality.productivityStack': 'Stos Produktywności',
        'personality.productivityStackTag': '5+ narzędzi do pracy — energia power usera',
        'personality.musicSnob': 'Snob Muzyczny',
        'personality.musicSnobTag': 'Wiele serwisów muzycznych — wymagające ucho',
        'personality.spiraler': 'Spirala Subskrypcji',
        'personality.spiralerTag': '10+ aktywnych subskrypcji. Może czas na audyt?',
        'personality.minimalist': 'Zdrowy Minimalista',
        'personality.minimalistTag': 'Mało subskrypcji, wszystkie wysoko ocenione. Inspiracja.',
        'personality.forgotten': 'Zapomniany',
        'personality.forgottenTag': 'Masz subskrypcje starsze niż rok, których nigdy nie oceniasz',
        'personality.starting': 'Dopiero zaczynasz',
        'personality.startingTag': 'Witaj — każdy wyciek zaczyna się od jednej kropli',
        'bench.title': 'Jak wypadasz',
        'bench.expected': 'Średnia dla {count} subów: {expected}',
        'bench.percentile': 'Top {pct}% użytkowników',
        'bench.lower': 'poniżej średniej',
        'bench.average': 'w średniej',
        'bench.higher': 'powyżej średniej',
        'bench.muchHigher': 'znacznie powyżej',
        'menu.whatif': 'Kalkulator "Co jeśli"',
        'menu.whatifSub': 'Wybierz suby do anulowania — zobacz oszczędności na żywo',
        'whatif.title': 'Kalkulator "Co jeśli"',
        'whatif.blurb': 'Dotknij subskrypcji, aby oznaczyć je jako anulowane w tym scenariuszu. Pokażemy, ile zaoszczędzisz bez zmiany prawdziwych danych.',
        'whatif.empty': 'Brak aktywnych subskrypcji do symulacji.',
        'whatif.suggestBtn': 'Sugerowane wybory',
        'whatif.clearBtn': 'Wyczyść wszystko',
        'whatif.summarySelected': 'Wybrano {n}',
        'whatif.summarySavings': '{monthly}/mies · {yearly}/rok',
        'whatif.investedNote': 'Zainwestowane na 7%: {y5} za 5 lat, {y10} za 10 lat',
        'home.notesLabel': 'Notatki',
        'streak.days': 'dni serii',
        'streak.msg': 'Czy oparłeś się dziś nowej subskrypcji?',
        'streak.btn': 'Zostałem czysty!',
        'streak.done': 'Czysto dzisiaj! ✨',
        'streak.msgDone': 'Dobra robota! Do zobaczenia jutro.',
        'toast.streakUpdated': 'Seria zaktualizowana! 🔥',
        'field.tags': 'Tagi',
        'field.tagsPh': 'praca, rodzina, rozważane, …',
        'field.tagsNote': 'Dowolne etykiety. Oddzielaj przecinkami.',
        'home.tagFilter': 'Filtruj wg tagu',
        'home.allTags': 'Wszystkie tagi',
        'lifetime.inflationTitle': 'Jeśli ceny będą dalej rosnąć',
        'lifetime.inflationNote': 'Większość subów podnosi ceny o 3-7%/rok. Prognozujemy 5% — typowe dla SaaS.',
        'lifetime.inflated10y': '10 lat przy +5%/rok',
        'menu.compare': 'Porównaj obok siebie',
        'menu.compareSub': 'Wybierz 2 lub 3 do porównania',
        'compare.title': 'Porównaj obok siebie',
        'compare.blurb': 'Wybierz 2 lub 3 subskrypcje. Zestawimy je, abyś widział, którą wyciąć.',
        'compare.pickPrompt': 'Dotknij, aby wybrać do 3 subskrypcji',
        'compare.minPrompt': 'Wybierz co najmniej 2 subskrypcje do porównania',
        'compare.monthly': 'Miesięcznie',
        'compare.yearly': 'Rocznie',
        'compare.lifetime': 'Zapłacono dotychczas',
        'compare.rating': 'Ocena',
        'compare.cancelDiff': 'Trudność anulowania',
        'compare.alternatives': 'Alternatywy',
        'compare.notRated': '— brak oceny',
        'compare.diff.easy': 'Łatwa',
        'compare.diff.medium': 'Średnia',
        'compare.diff.hard': 'Trudna',
        'compare.diff.unknown': 'Nieznana',
        'compare.altCountN': '{n} opcji',
        'compare.minutesAbbr': '{n} min'
    },
    'sv': {
        'menu.activity': 'Aktivitetslogg',
        'menu.activitySub': 'Se varje ändring du gjort',
        'activity.title': 'Aktivitetslogg',
        'activity.empty': 'Ingen aktivitet än. Lägg till en prenumeration för att börja.',
        'activity.added': 'Lade till {name}',
        'activity.edited': 'Ändrade {name}',
        'activity.cancelled': 'Avbröt {name}',
        'activity.paused': 'Pausade {name}',
        'activity.resumed': 'Återupptog {name}',
        'activity.restored': 'Återställde {name}',
        'activity.deleted': 'Tog bort {name}',
        'activity.imported': 'Importerade {n} prenumerationer',
        'personality.title': 'Din prenumerationspersonlighet',
        'personality.quietCutter': 'Den tysta avslutaren',
        'personality.quietCutterTag': 'Du har avslutat flera prenumerationer i år — vinner i tystnad',
        'personality.bundleMaster': 'Paketmästare',
        'personality.bundleMasterTag': 'Du vet hur man staplar besparingar',
        'personality.streamingJunkie': 'Streamingjunkie',
        'personality.streamingJunkieTag': '3+ nöjesprenumerationer — du älskar dina serier',
        'personality.aiHoarder': 'AI-samlare',
        'personality.aiHoarderTag': 'Samlar AI-verktyg snabbare än de släpper uppdateringar',
        'personality.productivityStack': 'Produktivitetsstacken',
        'personality.productivityStackTag': '5+ arbetsverktyg — power user-energi',
        'personality.musicSnob': 'Musiksnobb',
        'personality.musicSnobTag': 'Flera musiktjänster — kräset öra',
        'personality.spiraler': 'Prenumerationsspiralen',
        'personality.spiralerTag': '10+ aktiva prenumerationer. Kanske dags för en genomgång?',
        'personality.minimalist': 'Den hälsosamma minimalisten',
        'personality.minimalistTag': 'Få prenumerationer, alla högt betygsatta. Inspiration.',
        'personality.forgotten': 'Den glömske',
        'personality.forgottenTag': 'Du har prenumerationer äldre än ett år som du aldrig betygsätter',
        'personality.starting': 'Nyss börjat',
        'personality.startingTag': 'Välkommen — varje läcka börjar med en droppe',
        'bench.title': 'Hur du ligger till',
        'bench.expected': 'Snitt för {count} subs: {expected}',
        'bench.percentile': 'Topp {pct}% av användarna',
        'bench.lower': 'under snittet',
        'bench.average': 'på snittet',
        'bench.higher': 'över snittet',
        'bench.muchHigher': 'långt över',
        'menu.whatif': 'Vad-händer-om kalkylator',
        'menu.whatifSub': 'Välj subs att avsluta — se besparingen live',
        'whatif.title': 'Vad-händer-om kalkylator',
        'whatif.blurb': 'Tryck på prenumerationer för att markera dem som avslutade i detta scenario. Vi visar vad du skulle spara utan att ändra dina riktiga data.',
        'whatif.empty': 'Inga aktiva prenumerationer att simulera.',
        'whatif.suggestBtn': 'Föreslagna val',
        'whatif.clearBtn': 'Rensa allt',
        'whatif.summarySelected': '{n} valda',
        'whatif.summarySavings': '{monthly}/mån · {yearly}/år',
        'whatif.investedNote': 'Investerat vid 7%: {y5} om 5 år, {y10} om 10 år',
        'home.notesLabel': 'Anteckningar',
        'streak.days': 'dagars svit',
        'streak.msg': 'Motstod du en ny prenumeration idag?',
        'streak.btn': 'Jag höll mig ren!',
        'streak.done': 'Ren idag! ✨',
        'streak.msgDone': 'Bra jobbat! Ses imorgon.',
        'toast.streakUpdated': 'Svit uppdaterad! 🔥',
        'field.tags': 'Taggar',
        'field.tagsPh': 'jobb, familj, funderar, …',
        'field.tagsNote': 'Fria etiketter. Separera med kommatecken.',
        'home.tagFilter': 'Filtrera efter tagg',
        'home.allTags': 'Alla taggar',
        'lifetime.inflationTitle': 'Om priserna fortsätter stiga',
        'lifetime.inflationNote': 'De flesta subs höjer priserna 3-7%/år. Vi räknar med 5% — typiskt för SaaS.',
        'lifetime.inflated10y': '10 år vid +5%/år',
        'menu.compare': 'Jämför sida vid sida',
        'menu.compareSub': 'Välj 2 eller 3 att jämföra',
        'compare.title': 'Jämför sida vid sida',
        'compare.blurb': 'Välj 2 eller 3 prenumerationer. Vi ställer upp dem så du kan se vilken du ska ta bort.',
        'compare.pickPrompt': 'Tryck för att välja upp till 3 prenumerationer',
        'compare.minPrompt': 'Välj minst 2 prenumerationer att jämföra',
        'compare.monthly': 'Månadsvis',
        'compare.yearly': 'Årsvis',
        'compare.lifetime': 'Betalat hittills',
        'compare.rating': 'Betyg',
        'compare.cancelDiff': 'Uppsägningssvårighet',
        'compare.alternatives': 'Alternativ',
        'compare.notRated': '— ej betygsatt',
        'compare.diff.easy': 'Lätt',
        'compare.diff.medium': 'Medel',
        'compare.diff.hard': 'Svår',
        'compare.diff.unknown': 'Okänd',
        'compare.altCountN': '{n} alternativ',
        'compare.minutesAbbr': '{n} min'
    },
    'cs': {
        'menu.activity': 'Protokol aktivit',
        'menu.activitySub': 'Zobrazit každou provedenou změnu',
        'activity.title': 'Protokol aktivit',
        'activity.empty': 'Zatím žádná aktivita. Přidejte předplatné a začněte.',
        'activity.added': 'Přidáno {name}',
        'activity.edited': 'Upraveno {name}',
        'activity.cancelled': 'Zrušeno {name}',
        'activity.paused': 'Pozastaveno {name}',
        'activity.resumed': 'Obnoveno {name}',
        'activity.restored': 'Obnoveno {name}',
        'activity.deleted': 'Smazáno {name}',
        'activity.imported': 'Importováno {n} předplatných',
        'personality.title': 'Vaše osobnost předplatitele',
        'personality.quietCutter': 'Tichý řezník',
        'personality.quietCutterTag': 'Letos jste zrušili několik předplatných — tiché vítězství',
        'personality.bundleMaster': 'Mistr balíčků',
        'personality.bundleMasterTag': 'Víte, jak vrstvit úspory',
        'personality.streamingJunkie': 'Závislák na streamování',
        'personality.streamingJunkieTag': '3+ zábavní předplatná — milujete své seriály',
        'personality.aiHoarder': 'Sběratel AI',
        'personality.aiHoarderTag': 'Sbíráte AI nástroje rychleji, než vydávají aktualizace',
        'personality.productivityStack': 'Produktivní stack',
        'personality.productivityStackTag': '5+ pracovních nástrojů — energie power usera',
        'personality.musicSnob': 'Hudební snob',
        'personality.musicSnobTag': 'Více hudebních služeb — náročné ucho',
        'personality.spiraler': 'Spirála předplatného',
        'personality.spiralerTag': '10+ aktivních předplatných. Možná je čas na audit?',
        'personality.minimalist': 'Zdravý minimalista',
        'personality.minimalistTag': 'Málo předplatných, všechna vysoko hodnocená. Inspirace.',
        'personality.forgotten': 'Zapomnětlivý',
        'personality.forgottenTag': 'Máte předplatná starší než rok, která nikdy nehodnotíte',
        'personality.starting': 'Právě začínáte',
        'personality.startingTag': 'Vítejte — každý únik začíná jednou kapkou',
        'bench.title': 'Jak si vedete',
        'bench.expected': 'Průměr pro {count} předplatných: {expected}',
        'bench.percentile': 'Mezi top {pct}% uživatelů',
        'bench.lower': 'pod průměrem',
        'bench.average': 'v průměru',
        'bench.higher': 'nad průměrem',
        'bench.muchHigher': 'výrazně nad',
        'menu.whatif': 'Kalkulačka "Co když"',
        'menu.whatifSub': 'Vyberte předplatná ke zrušení — sledujte úspory živě',
        'whatif.title': 'Kalkulačka "Co když"',
        'whatif.blurb': 'Klepnutím na předplatná je v tomto scénáři označíte jako zrušená. Ukážeme vám, kolik byste ušetřili, aniž bychom měnili vaše skutečná data.',
        'whatif.empty': 'Žádná aktivní předplatná k simulaci.',
        'whatif.suggestBtn': 'Doporučené tipy',
        'whatif.clearBtn': 'Vymazat vše',
        'whatif.summarySelected': 'Vybráno {n}',
        'whatif.summarySavings': '{monthly}/měs · {yearly}/rok',
        'whatif.investedNote': 'Investováno při 7%: {y5} za 5 let, {y10} za 10 let',
        'home.notesLabel': 'Poznámky',
        'streak.days': 'dnů v řadě',
        'streak.msg': 'Odolali jste dnes novému předplatnému?',
        'streak.btn': 'Zůstal jsem čistý!',
        'streak.done': 'Dnes čistý! ✨',
        'streak.msgDone': 'Dobrá práce! Uvidíme se zítra.',
        'toast.streakUpdated': 'Série aktualizována! 🔥',
        'field.tags': 'Štítky',
        'field.tagsPh': 'práce, rodina, zvažuji, …',
        'field.tagsNote': 'Volné štítky. Oddělujte čárkami.',
        'home.tagFilter': 'Filtrovat podle štítku',
        'home.allTags': 'Všechny štítky',
        'lifetime.inflationTitle': 'Pokud ceny nadále porostou',
        'lifetime.inflationNote': 'Většina předplatných zvyšuje ceny o 3-7 % ročně. Projektujeme 5 % — typické pro SaaS.',
        'lifetime.inflated10y': '10 let při +5%/rok',
        'menu.compare': 'Porovnat vedle sebe',
        'menu.compareSub': 'Vyberte 2 nebo 3 k porovnání',
        'compare.title': 'Porovnat vedle sebe',
        'compare.blurb': 'Vyberte 2 nebo 3 předplatná. Seřadíme je vedle sebe, abyste viděli, které zrušit.',
        'compare.pickPrompt': 'Klepnutím vyberte až 3 předplatná',
        'compare.minPrompt': 'Vyberte alespoň 2 předplatná k porovnání',
        'compare.monthly': 'Měsíčně',
        'compare.yearly': 'Ročně',
        'compare.lifetime': 'Dosud zaplaceno',
        'compare.rating': 'Hodnocení',
        'compare.cancelDiff': 'Obtížnost zrušení',
        'compare.alternatives': 'Alternativy',
        'compare.notRated': '— nehodnoceno',
        'compare.diff.easy': 'Snadná',
        'compare.diff.medium': 'Střední',
        'compare.diff.hard': 'Těžká',
        'compare.diff.unknown': 'Neznámá',
        'compare.altCountN': '{n} možností',
        'compare.minutesAbbr': '{n} min'
    },
    'ru': {
        'menu.activity': 'Журнал активности',
        'menu.activitySub': 'Смотрите каждое сделанное вами изменение',
        'activity.title': 'Журнал активности',
        'activity.empty': 'Активности пока нет. Добавьте подписку, чтобы начать.',
        'activity.added': 'Добавлено {name}',
        'activity.edited': 'Изменено {name}',
        'activity.cancelled': 'Отменено {name}',
        'activity.paused': 'Приостановлено {name}',
        'activity.resumed': 'Возобновлено {name}',
        'activity.restored': 'Восстановлено {name}',
        'activity.deleted': 'Удалено {name}',
        'activity.imported': 'Импортировано {n} подписок',
        'personality.title': 'Ваш тип подписчика',
        'personality.quietCutter': 'Тихий резчик',
        'personality.quietCutterTag': 'Вы отменили несколько подписок в этом году — тихая победа',
        'personality.bundleMaster': 'Мастер пакетов',
        'personality.bundleMasterTag': 'Вы знаете, как экономить на наборах',
        'personality.streamingJunkie': 'Стриминг-зависимый',
        'personality.streamingJunkieTag': '3+ развлекательные подписки — вы любите свои сериалы',
        'personality.aiHoarder': 'ИИ-коллекционер',
        'personality.aiHoarderTag': 'Собираете ИИ-инструменты быстрее, чем выходят обновления',
        'personality.productivityStack': 'Продуктивный стек',
        'personality.productivityStackTag': '5+ рабочих инструментов — энергия продвинутого пользователя',
        'personality.musicSnob': 'Музыкальный сноб',
        'personality.musicSnobTag': 'Несколько музыкальных сервисов — взыскательный слух',
        'personality.spiraler': 'Подписочная спираль',
        'personality.spiralerTag': '10+ активных подписок. Может, пора провести аудит?',
        'personality.minimalist': 'Здоровый минималист',
        'personality.minimalistTag': 'Мало подписок, все с высоким рейтингом. Вдохновляет.',
        'personality.forgotten': 'Забывчивый',
        'personality.forgottenTag': 'У вас есть подписки старше года, которые вы никогда не оцениваете',
        'personality.starting': 'Только начало',
        'personality.startingTag': 'Добро пожаловать — любая утечка начинается с капли',
        'bench.title': 'Как вы выглядите на фоне других',
        'bench.expected': 'Среднее для {count} подписок: {expected}',
        'bench.percentile': 'В топ {pct}% трекеров',
        'bench.lower': 'ниже среднего',
        'bench.average': 'в среднем',
        'bench.higher': 'выше среднего',
        'bench.muchHigher': 'значительно выше',
        'menu.whatif': 'Калькулятор "Что если"',
        'menu.whatifSub': 'Выберите подписки для отмены — смотрите экономию в реальном времени',
        'whatif.title': 'Калькулятор "Что если"',
        'whatif.blurb': 'Нажимайте на подписки, чтобы пометить их как отмененные в этом сценарии. Мы покажем, сколько вы сэкономите, не меняя реальные данные.',
        'whatif.empty': 'Нет активных подписок для симуляции.',
        'whatif.suggestBtn': 'Рекомендуемые кандидаты',
        'whatif.clearBtn': 'Очистить всё',
        'whatif.summarySelected': 'Выбрано {n}',
        'whatif.summarySavings': '{monthly}/мес · {yearly}/год',
        'whatif.investedNote': 'Инвестировано под 7%: {y5} через 5 лет, {y10} через 10',
        'home.notesLabel': 'Заметки',
        'streak.days': 'дн. подряд',
        'streak.msg': 'Устояли перед новой подпиской сегодня?',
        'streak.btn': 'Я остался чист!',
        'streak.done': 'Чист сегодня! ✨',
        'streak.msgDone': 'Отличная работа! До завтра.',
        'toast.streakUpdated': 'Серия обновлена! 🔥',
        'field.tags': 'Теги',
        'field.tagsPh': 'работа, семья, думаю, …',
        'field.tagsNote': 'Любые метки. Разделяйте запятыми.',
        'home.tagFilter': 'Фильтр по тегу',
        'home.allTags': 'Все теги',
        'lifetime.inflationTitle': 'Если цены продолжат расти',
        'lifetime.inflationNote': 'Большинство подписок дорожают на 3-7% в год. Мы прогнозируем 5% — типично для SaaS.',
        'lifetime.inflated10y': '10 лет при +5%/год',
        'menu.compare': 'Сравнение бок о бок',
        'menu.compareSub': 'Выберите 2 или 3 для сравнения',
        'compare.title': 'Сравнение бок о бок',
        'compare.blurb': 'Выберите 2 или 3 подписки. Мы выстроим их в ряд, чтобы вы видели, какую отсечь.',
        'compare.pickPrompt': 'Нажмите, чтобы выбрать до 3 подписок',
        'compare.minPrompt': 'Выберите минимум 2 подписки для сравнения',
        'compare.monthly': 'В месяц',
        'compare.yearly': 'В год',
        'compare.lifetime': 'Выплачено всего',
        'compare.rating': 'Рейтинг',
        'compare.cancelDiff': 'Сложность отмены',
        'compare.alternatives': 'Альтернативы',
        'compare.notRated': '— без рейтинга',
        'compare.diff.easy': 'Легко',
        'compare.diff.medium': 'Средне',
        'compare.diff.hard': 'Сложно',
        'compare.diff.unknown': 'Неизвестно',
        'compare.altCountN': 'вариантов: {n}',
        'compare.minutesAbbr': '{n} мин'
    }
};

// Injection logic
for (const lang in allLangs) {
    const blockStartTag = `},    ${lang}: {`;
    let blockIndex = content.indexOf(blockStartTag);
    if (blockIndex === -1) continue;
    
    const keysStart = content.indexOf('{', blockIndex) + 1;
    const blockEnd = content.indexOf('},', keysStart);
    if (blockEnd === -1) continue;
    
    let blockContent = content.substring(keysStart, blockEnd);
    for (const key in allLangs[lang]) {
        const val = allLangs[lang][key].replace(/'/g, "\\'");
        const keyPattern = new RegExp(`'${key.replace('.', '\\.')}':\\s*'[^']*'`);
        if (blockContent.match(keyPattern)) {
            blockContent = blockContent.replace(keyPattern, `'${key}': '${val}'`);
        } else {
            blockContent += `\n      '${key}': '${val}',`;
        }
    }
    content = content.substring(0, keysStart) + blockContent + content.substring(blockEnd);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Complete robust injection finished!');
