const fs = require('fs');
const path = 'c:/Users/local_user/Documents/leakd/leakd/js/i18n.js';
let content = fs.readFileSync(path, 'utf8');

const allTranslations = {
    'pl': {
        'menu.activity': 'Dziennik aktywności',
        'menu.activitySub': 'Zobacz każdą wprowadzoną zmianę',
        'activity.title': 'Dziennik aktywności',
        'activity.empty': 'Brak aktywności. Dodaj subskrypcję, aby zacząć.',
        'activity.added': 'Dodano {name}',
        'activity.edited': 'Edytowano {name}',
        'activity.cancelled': 'Anulowano {name}',
        'activity.paused': 'Wstrzymano {name}',
        'activity.resumed': 'Wznowiono {name}',
        'activity.restored': 'Przywrócono {name}',
        'activity.deleted': 'Usunięto {name}',
        'activity.imported': 'Zaimportowano {n} subskrypcji',
        'personality.title': 'Twoja osobowość subskrypcyjna',
        'personality.quietCutter': 'Cichy Wycinacz',
        'personality.quietCutterTag': 'Anulowałeś kilka subskrypcji w tym roku — ciche zwycięstwo',
        'personality.bundleMaster': 'Mistrz Pakietów',
        'personality.bundleMasterTag': 'Wiesz, jak kumulować oszczędności',
        'personality.streamingJunkie': 'Uzależniony od Streamingu',
        'personality.streamingJunkieTag': '3+ subskrypcje rozrywkowe — kochasz swoje seriale',
        'personality.aiHoarder': 'Gromadzący AI',
        'personality.aiHoarderTag': 'Zbierasz narzędzia AI szybciej, niż one wypuszczają aktualizacje',
        'personality.productivityStack': 'Stos Produktywności',
        'personality.productivityStackTag': '5+ narzędzi do pracy — energia power usera',
        'personality.musicSnob': 'Snob Muzyczny',
        'personality.musicSnobTag': 'Wiele serwisów muzycznych — wymagające ucho',
        'personality.spiraler': 'Spirala Subskrypcji',
        'personality.spiralerTag': '10+ aktywnych subskrypcji. Może czas na audyt?',
        'personality.minimalist': 'Zdrowy Minimalista',
        'personality.minimalistTag': 'Mało subskrypcji, wszystkie wysoko ocenione. Inspiracja.',
        'personality.forgotten': 'Zapomniany',
        'personality.forgottenTag': 'Masz subskrypcje starsze niż rok, których nigdy nie oceniasz',
        'personality.starting': 'Dopiero zaczynasz',
        'personality.startingTag': 'Witaj — każdy wyciek zaczyna się od jednej kropli',
        'bench.title': 'Jak wypadasz',
        'bench.expected': 'Średnia dla {count} subów: {expected}',
        'bench.percentile': 'Top {pct}% użytkowników',
        'bench.lower': 'poniżej średniej',
        'bench.average': 'w średniej',
        'bench.higher': 'powyżej średniej',
        'bench.muchHigher': 'znacznie powyżej',
        'menu.whatif': 'Kalkulator "Co jeśli"',
        'menu.whatifSub': 'Wybierz suby do anulowania — zobacz oszczędności na żywo',
        'whatif.title': 'Kalkulator "Co jeśli"',
        'whatif.blurb': 'Dotknij subskrypcji, aby oznaczyć je jako anulowane w tym scenariu. Pokażemy, ile zaoszczędzisz bez zmiany prawdziwych danych.',
        'whatif.empty': 'Brak aktywnych subskrypcji do symulacji.',
        'whatif.suggestBtn': 'Sugerowane wybory',
        'whatif.clearBtn': 'Wyczyść wszystko',
        'whatif.summarySelected': 'Wybrano {n}',
        'whatif.summarySavings': '{monthly}/mies · {yearly}/rok',
        'whatif.investedNote': 'Zainwestowane na 7%: {y5} za 5 lat, {y10} za 10 lat',
        'home.notesLabel': 'Notatki',
        'streak.days': 'dni serii',
        'streak.msg': 'Czy oparłeś się dziś nowej subskrypcji?',
        'streak.btn': 'Zostałem czysty!',
        'streak.done': 'Czysto dzisiaj! ✨',
        'streak.msgDone': 'Dobra robota! Do zobaczenia jutro.',
        'toast.streakUpdated': 'Seria zaktualizowana! 🔥',
        'field.tags': 'Tagi',
        'field.tagsPh': 'praca, rodzina, rozważane, …',
        'field.tagsNote': 'Dowolne etykiety. Oddzielaj przecinkami.',
        'home.tagFilter': 'Filtruj wg tagu',
        'home.allTags': 'Wszystkie tagi',
        'lifetime.inflationTitle': 'Jeśli ceny będą dalej rosnąć',
        'lifetime.inflationNote': 'Większość subów podnosi ceny o 3-7%/rok. Prognozujemy 5% — typowe dla SaaS.',
        'lifetime.inflated10y': '10 lat przy +5%/rok',
        'menu.compare': 'Porównaj obok siebie',
        'menu.compareSub': 'Wybierz 2 lub 3 do porównania',
        'compare.title': 'Porównaj obok siebie',
        'compare.blurb': 'Wybierz 2 lub 3 subskrypcje. Zestawimy je, abyś widział, którą wyciąć.',
        'compare.pickPrompt': 'Dotknij, aby wybrać do 3 subskrypcji',
        'compare.minPrompt': 'Wybierz co najmniej 2 subskrypcje do porównania',
        'compare.monthly': 'Miesięcznie',
        'compare.yearly': 'Rocznie',
        'compare.lifetime': 'Zapłacono dotychczas',
        'compare.rating': 'Ocena',
        'compare.cancelDiff': 'Trudność anulowania',
        'compare.alternatives': 'Alternatywy',
        'compare.notRated': '— brak oceny',
        'compare.diff.easy': 'Łatwa',
        'compare.diff.medium': 'Średnia',
        'compare.diff.hard': 'Trudna',
        'compare.diff.unknown': 'Nieznana',
        'compare.altCountN': '{n} opcji',
        'compare.minutesAbbr': '{n} min'
    },
    'sv': {
        'menu.activity': 'Aktivitetslogg',
        'menu.activitySub': 'Se varje ändring du gjort',
        'activity.title': 'Aktivitetslogg',
        'activity.empty': 'Ingen aktivitet än. Lägg till en prenumeration för att börja.',
        'activity.added': 'Lade till {name}',
        'activity.edited': 'Ändrade {name}',
        'activity.cancelled': 'Avbröt {name}',
        'activity.paused': 'Pausade {name}',
        'activity.resumed': 'Återupptog {name}',
        'activity.restored': 'Återställde {name}',
        'activity.deleted': 'Tog bort {name}',
        'activity.imported': 'Importerade {n} prenumerationer',
        'personality.title': 'Din prenumerationspersonlighet',
        'personality.quietCutter': 'Den tysta avslutaren',
        'personality.quietCutterTag': 'Du har avslutat flera prenumerationer i år — vinner i tystnad',
        'personality.bundleMaster': 'Paketmästare',
        'personality.bundleMasterTag': 'Du vet hur man staplar besparingar',
        'personality.streamingJunkie': 'Streamingjunkie',
        'personality.streamingJunkieTag': '3+ nöjesprenumerationer — du älskar dina serier',
        'personality.aiHoarder': 'AI-samlare',
        'personality.aiHoarderTag': 'Samlar AI-verktyg snabbare än de släpper uppdateringar',
        'personality.productivityStack': 'Produktivitetsstacken',
        'personality.productivityStackTag': '5+ arbetsverktyg — power user-energi',
        'personality.musicSnob': 'Musiksnobb',
        'personality.musicSnobTag': 'Flera musiktjänster — kräset öra',
        'personality.spiraler': 'Prenumerationsspiralen',
        'personality.spiralerTag': '10+ aktiva prenumerationer. Kanske dags för en genomgång?',
        'personality.minimalist': 'Den hälsosamma minimalisten',
        'personality.minimalistTag': 'Få prenumerationer, alla högt betygsatta. Inspiration.',
        'personality.forgotten': 'Den glömske',
        'personality.forgottenTag': 'Du har prenumerationer äldre än ett år som du aldrig betygsätter',
        'personality.starting': 'Nyss börjat',
        'personality.startingTag': 'Välkommen — varje läcka börjar med en droppe',
        'bench.title': 'Hur du ligger till',
        'bench.expected': 'Snitt för {count} subs: {expected}',
        'bench.percentile': 'Topp {pct}% av användarna',
        'bench.lower': 'under snittet',
        'bench.average': 'på snittet',
        'bench.higher': 'över snittet',
        'bench.muchHigher': 'långt över',
        'menu.whatif': 'Vad-händer-om kalkylator',
        'menu.whatifSub': 'Välj subs att avsluta — se besparingen live',
        'whatif.title': 'Vad-händer-om kalkylator',
        'whatif.blurb': 'Tryck på prenumerationer för att markera dem som avslutade i detta scenario. Vi visar vad du skulle spara utan att ändra dina riktiga data.',
        'whatif.empty': 'Inga aktiva prenumerationer att simulera.',
        'whatif.suggestBtn': 'Föreslagna val',
        'whatif.clearBtn': 'Rensa allt',
        'whatif.summarySelected': '{n} valda',
        'whatif.summarySavings': '{monthly}/mån · {yearly}/år',
        'whatif.investedNote': 'Investerat vid 7%: {y5} om 5 år, {y10} om 10 år',
        'home.notesLabel': 'Anteckningar',
        'streak.days': 'dagars svit',
        'streak.msg': 'Motstod du en ny prenumeration idag?',
        'streak.btn': 'Jag höll mig ren!',
        'streak.done': 'Ren idag! ✨',
        'streak.msgDone': 'Bra jobbat! Ses imorgon.',
        'toast.streakUpdated': 'Svit uppdaterad! 🔥',
        'field.tags': 'Taggar',
        'field.tagsPh': 'jobb, familj, funderar, …',
        'field.tagsNote': 'Fria etiketter. Separera med kommatecken.',
        'home.tagFilter': 'Filtrera efter tagg',
        'home.allTags': 'Alla taggar',
        'lifetime.inflationTitle': 'Om priserna fortsätter stiga',
        'lifetime.inflationNote': 'De flesta subs höjer priserna 3-7%/år. Vi räknar med 5% — typiskt för SaaS.',
        'lifetime.inflated10y': '10 år vid +5%/år',
        'menu.compare': 'Jämför sida vid sida',
        'menu.compareSub': 'Välj 2 eller 3 att jämföra',
        'compare.title': 'Jämför sida vid sida',
        'compare.blurb': 'Välj 2 eller 3 prenumerationer. Vi ställer upp dem så du kan se vilken du ska ta bort.',
        'compare.pickPrompt': 'Tryck för att välja upp till 3 prenumerationer',
        'compare.minPrompt': 'Välj minst 2 prenumerationer att jämföra',
        'compare.monthly': 'Månadsvis',
        'compare.yearly': 'Årsvis',
        'compare.lifetime': 'Betalat hittills',
        'compare.rating': 'Betyg',
        'compare.cancelDiff': 'Uppsägningssvårighet',
        'compare.alternatives': 'Alternativ',
        'compare.notRated': '— ej betygsatt',
        'compare.diff.easy': 'Lätt',
        'compare.diff.medium': 'Medel',
        'compare.diff.hard': 'Svår',
        'compare.diff.unknown': 'Okänd',
        'compare.altCountN': '{n} alternativ',
        'compare.minutesAbbr': '{n} min'
    },
    'cs': {
        'menu.activity': 'Protokol aktivit',
        'menu.activitySub': 'Zobrazit každou provedenou změnu',
        'activity.title': 'Protokol aktivit',
        'activity.empty': 'Zatím žádná aktivita. Přidejte předplatné a začněte.',
        'activity.added': 'Přidáno {name}',
        'activity.edited': 'Upraveno {name}',
        'activity.cancelled': 'Zrušeno {name}',
        'activity.paused': 'Pozastaveno {name}',
        'activity.resumed': 'Obnoveno {name}',
        'activity.restored': 'Obnoveno {name}',
        'activity.deleted': 'Smazáno {name}',
        'activity.imported': 'Importováno {n} předplatných',
        'personality.title': 'Vaše osobnost předplatitele',
        'personality.quietCutter': 'Tichý řezník',
        'personality.quietCutterTag': 'Letos jste zrušili několik předplatných — tiché vítězství',
        'personality.bundleMaster': 'Mistr balíčků',
        'personality.bundleMasterTag': 'Víte, jak vrstvit úspory',
        'personality.streamingJunkie': 'Závislák na streamování',
        'personality.streamingJunkieTag': '3+ zábavní předplatná — milujete své seriály',
        'personality.aiHoarder': 'Sběratel AI',
        'personality.aiHoarderTag': 'Sbíráte AI nástroje rychleji, než vydávají aktualizace',
        'personality.productivityStack': 'Produktivní stack',
        'personality.productivityStackTag': '5+ pracovních nástrojů — energie power usera',
        'personality.musicSnob': 'Hudební snob',
        'personality.musicSnobTag': 'Více hudebních služeb — náročné ucho',
        'personality.spiraler': 'Spirála předplatného',
        'personality.spiralerTag': '10+ aktivních předplatných. Možná je čas na audit?',
        'personality.minimalist': 'Zdravý minimalista',
        'personality.minimalistTag': 'Málo předplatných, všechna vysoko hodnocená. Inspirace.',
        'personality.forgotten': 'Zapomnětlivý',
        'personality.forgottenTag': 'Máte předplatná starší než rok, která nikdy nehodnotíte',
        'personality.starting': 'Právě začínáte',
        'personality.startingTag': 'Vítejte — každý únik začíná jednou kapkou',
        'bench.title': 'Jak si vedete',
        'bench.expected': 'Průměr pro {count} předplatných: {expected}',
        'bench.percentile': 'Mezi top {pct}% uživatelů',
        'bench.lower': 'pod průměrem',
        'bench.average': 'v průměru',
        'bench.higher': 'nad průměrem',
        'bench.muchHigher': 'výrazně nad',
        'menu.whatif': 'Kalkulačka "Co když"',
        'menu.whatifSub': 'Vyberte předplatná ke zrušení — sledujte úspory živě',
        'whatif.title': 'Kalkulačka "Co když"',
        'whatif.blurb': 'Klepnutím na předplatná je v tomto scénáři označíte jako zrušená. Ukážeme vám, kolik byste ušetřili, aniž bychom měnili vaše skutečná data.',
        'whatif.empty': 'Žádná aktivní předplatná k simulaci.',
        'whatif.suggestBtn': 'Doporučené tipy',
        'whatif.clearBtn': 'Vymazat vše',
        'whatif.summarySelected': 'Vybráno {n}',
        'whatif.summarySavings': '{monthly}/měs · {yearly}/rok',
        'whatif.investedNote': 'Investováno při 7%: {y5} za 5 let, {y10} za 10 let',
        'home.notesLabel': 'Poznámky',
        'streak.days': 'dnů v řadě',
        'streak.msg': 'Odolali jste dnes novému předplatnému?',
        'streak.btn': 'Zůstal jsem čistý!',
        'streak.done': 'Dnes čistý! ✨',
        'streak.msgDone': 'Dobrá práce! Uvidíme se zítra.',
        'toast.streakUpdated': 'Série aktualizována! 🔥',
        'field.tags': 'Štítky',
        'field.tagsPh': 'práce, rodina, zvažuji, …',
        'field.tagsNote': 'Volné štítky. Oddělujte čárkami.',
        'home.tagFilter': 'Filtrovat podle štítku',
        'home.allTags': 'Všechny štítky',
        'lifetime.inflationTitle': 'Pokud ceny nadále porostou',
        'lifetime.inflationNote': 'Většina předplatných zvyšuje ceny o 3-7 % ročně. Projektujeme 5 % — typické pro SaaS.',
        'lifetime.inflated10y': '10 let při +5%/rok',
        'menu.compare': 'Porovnat vedle sebe',
        'menu.compareSub': 'Vyberte 2 nebo 3 k porovnání',
        'compare.title': 'Porovnat vedle sebe',
        'compare.blurb': 'Vyberte 2 oder 3 předplatná. Seřadíme je vedle sebe, abyste viděli, které zrušit.',
        'compare.pickPrompt': 'Klepnutím vyberte až 3 předplatná',
        'compare.minPrompt': 'Vyberte alespoň 2 předplatná k porovnání',
        'compare.monthly': 'Měsíčně',
        'compare.yearly': 'Ročně',
        'compare.lifetime': 'Dosud zaplaceno',
        'compare.rating': 'Hodnocení',
        'compare.cancelDiff': 'Obtížnost zrušení',
        'compare.alternatives': 'Alternativy',
        'compare.notRated': '— nehodnoceno',
        'compare.diff.easy': 'Snadná',
        'compare.diff.medium': 'Střední',
        'compare.diff.hard': 'Těžká',
        'compare.diff.unknown': 'Neznámá',
        'compare.altCountN': '{n} možností',
        'compare.minutesAbbr': '{n} min'
    },
    'ja': {
        'menu.activity': 'アクティビティログ',
        'menu.activitySub': '行ったすべての変更を確認する',
        'activity.title': 'アクティビティログ',
        'activity.empty': 'アクティビティはまだありません。サブスクを追加して始めましょう。',
        'activity.added': '{name} を追加しました',
        'activity.edited': '{name} を編集しました',
        'activity.cancelled': '{name} をキャンセルしました',
        'activity.paused': '{name} を一時停止しました',
        'activity.resumed': '{name} を再開しました',
        'activity.restored': '{name} を復元しました',
        'activity.deleted': '{name} を削除しました',
        'activity.imported': '{n} 個のサブスクをインポートしました',
        'personality.title': 'あなたのサブスクタイプ',
        'personality.quietCutter': '静かなる解約者',
        'personality.quietCutterTag': '今年、複数のサブスクを解約しました — 静かな勝利です',
        'personality.bundleMaster': 'セット割の達人',
        'personality.bundleMasterTag': '節約を積み重ねる方法を知っています',
        'personality.streamingJunkie': 'ストリーミング中毒',
        'personality.streamingJunkieTag': '3つ以上のエンタメサブスク — ドラマが大好きです',
        'personality.aiHoarder': 'AIコレクター',
        'personality.aiHoarderTag': 'アップデートよりも早くAIツールを集めています',
        'personality.productivityStack': '生産性スタック',
        'personality.productivityStackTag': '5つ以上の仕事ツール — パワーユーザーのエネルギー',
        'personality.musicSnob': '音楽スノッブ',
        'personality.musicSnobTag': '複数の音楽サービス — こだわりの耳',
        'personality.spiraler': 'サブスクの螺旋',
        'personality.spiralerTag': '10以上の有効なサブスク。そろそろ見直しの時期かも？',
        'personality.minimalist': '健全なミニマリスト',
        'personality.minimalistTag': 'サブスクが少なく、すべて高評価。インスピレーション。',
        'personality.forgotten': '忘れん坊',
        'personality.forgottenTag': '1年以上評価していない古いサブスクがあります',
        'personality.starting': '始めたばかり',
        'personality.startingTag': 'ようこそ — すべての漏れは一滴から始まります',
        'bench.title': '比較結果',
        'bench.expected': '{count} 個のサブスク平均: {expected}',
        'bench.percentile': '全ユーザーの上位 {pct}%',
        'bench.lower': '平均以下',
        'bench.average': '平均的',
        'bench.higher': '平均以上',
        'bench.muchHigher': '大幅に上回っています',
        'menu.whatif': '「もしも」シミュレーター',
        'menu.whatifSub': '解約するサブスクを選んで節約額を確認',
        'whatif.title': '「もしも」シミュレーター',
        'whatif.blurb': 'サブスクをタップして、このシナリオで解約済みとしてマークします。実際のデータを変更せずに、どれだけ節約できるかを示します。',
        'whatif.empty': 'シミュレーションできる有効なサブスクがありません。',
        'whatif.suggestBtn': 'おすすめの候補',
        'whatif.clearBtn': 'すべてクリア',
        'whatif.summarySelected': '{n} 個選択',
        'whatif.summarySavings': '{monthly}/月 · {yearly}/年',
        'whatif.investedNote': '7%で運用した場合: 5年で {y5}、10年で {y10}',
        'home.notesLabel': 'メモ',
        'streak.days': '日連続',
        'streak.msg': '今日は新しいサブスクを我慢できましたか？',
        'streak.btn': '我慢できました！',
        'streak.done': '今日はクリーンです！ ✨',
        'streak.msgDone': 'お疲れ様！また明日お会いしましょう。',
        'toast.streakUpdated': 'ストリークを更新しました！ 🔥',
        'field.tags': 'タグ',
        'field.tagsPh': '仕事、家族、検討中、…',
        'field.tagsNote': '自由なラベル。カンマで区切ってください。',
        'home.tagFilter': 'タグでフィルター',
        'home.allTags': 'すべてのタグ',
        'lifetime.inflationTitle': '物価が上がり続けたら',
        'lifetime.inflationNote': 'ほとんどのサブスクは年3-7%値上がりします。SaaSの標準である5%で予測します。',
        'lifetime.inflated10y': '10年後のコスト (+5%/年)',
        'menu.compare': '並べて比較',
        'menu.compareSub': '2つまたは3つ選んで比較',
        'compare.title': '並べて比較',
        'compare.blurb': '2つまたは3つのサブスクを選択してください。どれを削るべきか判断しやすいように並べて表示します。',
        'compare.pickPrompt': 'タップして最大3つまで選択',
        'compare.minPrompt': '比較するには少なくとも2つ選択してください',
        'compare.monthly': '月額',
        'compare.yearly': '年額',
        'compare.lifetime': 'これまでの合計支払い',
        'compare.rating': '評価',
        'compare.cancelDiff': '解約の難易度',
        'compare.alternatives': '代替サービス',
        'compare.notRated': '— 未評価',
        'compare.diff.easy': '簡単',
        'compare.diff.medium': '普通',
        'compare.diff.hard': '難しい',
        'compare.diff.unknown': '不明',
        'compare.altCountN': '{n} 個の選択肢',
        'compare.minutesAbbr': '{n} 分'
    }
};

// More batches can be added or handled in a loop.
// I'll handle the injection carefully now.

for (const lang in allTranslations) {
    // 1. Find the REAL language block in STRINGS
    // Pattern: },    lang: {
    const blockStartTag = `},    ${lang}: {`;
    let blockIndex = content.indexOf(blockStartTag);
    
    if (blockIndex === -1) {
        // Fallback for languages like 'hu' which might be differently formatted
        // but for now I know the pattern is mostly },    lang: {
        continue;
    }
    
    // We want to insert the keys inside this block.
    // I'll find where the keys start (after the opening brace)
    const keysStart = content.indexOf('{', blockIndex) + 1;
    // And where the block ends (the next }, )
    const blockEnd = content.indexOf('},', keysStart);
    
    if (blockEnd === -1) continue;
    
    let blockContent = content.substring(keysStart, blockEnd);
    
    for (const key in allTranslations[lang]) {
        const val = allTranslations[lang][key].replace(/'/g, "\\'");
        // Check if key already exists
        const keyPattern = new RegExp(`'${key.replace('.', '\\.')}':\\s*'[^']*'`);
        if (blockContent.match(keyPattern)) {
            blockContent = blockContent.replace(keyPattern, `'${key}': '${val}'`);
        } else {
            // Append at the end of the block
            blockContent += `\n      '${key}': '${val}',`;
        }
    }
    
    content = content.substring(0, keysStart) + blockContent + content.substring(blockEnd);
}

fs.writeFileSync(path, content, 'utf8');
console.log('Robust injection completed for selected languages!');
