const fs = require('fs');
const path = 'c:/Users/local_user/Documents/leakd/leakd/js/i18n.js';
let content = fs.readFileSync(path, 'utf8');

const cleanEnStrings = `    en: {
      // Header
      'app.tagline': "Where's your money leaking?",
      'header.notif': 'Notifications',
      'header.theme': 'Toggle theme',
      'header.menu': 'More',
      // Stats
      'stats.monthly': 'Monthly spend',
      'stats.yearly': 'Yearly total',
      'stats.active': 'Active subs',
      'stats.dueSoon': 'Due in 7 days',
      // Empty state
      'empty.title': 'No subscriptions yet',
      'empty.sub': 'Tap the + button or paste a list to start',
      'empty.paste': 'Paste subscriptions',
      // Categories
      'cat.all': 'All',
      'cat.Entertainment': 'Entertainment',
      'cat.Work': 'Work',
      'cat.Music': 'Music',
      'cat.Fitness': 'Fitness',
      'cat.Cloud': 'Cloud',
      'cat.Food': 'Food',
      'cat.News': 'News',
      'cat.Other': 'Other',
      'cat.new': '+ New Category (Pro)',
      'menu.pdf': 'PDF report (Pro)',
      'menu.pdfSub': 'Printable report for your accountant',
      // Cycle
      'cycle.monthly': 'Monthly',
      'cycle.yearly': 'Yearly',
      'cycle.weekly': 'Weekly',
      'cycle.mo': '/mo',
      'cycle.yr': '/yr',
      'cycle.wk': '/wk',
      // Bottom nav
      'nav.home': 'Home',
      'nav.insights': 'Insights',
      // Add modal
      'modal.add': 'Add subscription',
      'modal.edit': 'Edit subscription',
      'modal.orCustom': 'or add custom',
      'field.name': 'Name',
      'field.namePh': 'e.g. Netflix, Gym, Notion...',
      'field.price': 'Price',
      'field.cycle': 'Billing cycle',
      'field.category': 'Category',
      'field.nextDate': 'Next payment',
      'field.trial': 'This is a free trial',
      'field.trialEnd': 'Trial ends on',
      'field.business': 'This is a business expense',
      'filter.all': 'All',
      'filter.business': 'Business',
      'filter.personal': 'Personal',
      'field.lastUsed': 'Last used',
      'field.paused': 'Paused (not counted in total)',
      'btn.markUsed': 'Mark as used today',
      'btn.cancel': 'Cancel',
      'btn.save': 'Save',
      'btn.delete': 'Delete',
      'btn.done': 'Done',
      'btn.next': 'Next',
      'confirm.deleteSub': 'Delete this subscription?',
      // Currency
      'currency.choose': 'Choose currency',
      // Notification modal
      'notif.title': 'Notifications',
      'notif.blurb': 'Get a heads-up before subscriptions renew or free trials end. Everything runs on your device — no account, no server.',
      'notif.permission': 'Browser permission',
      'notif.allowed': 'Allowed',
      'notif.blocked': 'Blocked (change in browser settings)',
      'notif.notSet': 'Not set',
      'notif.unsupported': 'Not supported in this browser',
      'notif.enable': 'Enable notifications',
      'notif.beforeRenewal': 'Remind me before renewal',
      'notif.beforeTrial': 'Remind me before free trial ends',
      'notif.daysOption.0': 'On the day',
      'notif.daysOption.1': '1 day before',
      'notif.daysOption.2': '2 days before',
      'notif.daysOption.3': '3 days before',
      'notif.daysOption.5': '5 days before',
      'notif.daysOption.7': '1 week before',
      'notif.test': 'Send a test',
      'notif.deniedHint': 'Your browser blocked notifications for this site. Open the site settings (lock icon in the address bar) and allow notifications, then come back here.',
      'notif.testTitle': 'Leakd notifications are on',
      'notif.testBody': "You'll get a heads-up before your subscriptions renew.",
      'notif.on': 'Notifications on',
      'notif.off': 'Notifications off',
      // Insights
      'insights.ytd': 'YEAR-TO-DATE',
      'insights.paidIn': 'paid so far in',
      'insights.projection': '12-month projection',
      'insights.now': 'Now',
      'insights.byCategory': 'By category',
      'insights.suggestions': 'Smart suggestions',
      'insights.noData': 'No data yet',
      'insights.noSubs': 'Add some subscriptions to see suggestions',
      'insights.clean': 'Looking clean — no obvious leaks 🎉',
      'insights.shareTitle': 'Share your leak',
      'insights.shareSub': 'Generate a shareable image for Twitter, IG, or Reddit',
      'insights.generate': 'Generate',
      'panic.button': 'PANIKGOMB',
      'panic.sub': 'Spending is high. Time to cut the leaks.',
      'panic.title': 'Panic Mode: Active',
      'panic.intro': 'These subscriptions are costing you the most for the least value. Cut them now to stop the leak.',
      // Suggestions
      'sug.dup.title': '{count} overlapping {cat} subscriptions',
      'sug.dup.body': "You're paying for {names}. Keeping only one could save you up to <strong>{savings}/yr</strong>.",
      'sug.yearly.title': 'Switch {name} to yearly billing',
      'sug.yearly.body': 'Most services offer ~15–20% off when paid annually. Switching could save <strong>~{savings}/yr</strong>.',
      'sug.expensive.title': '{name} is your biggest leak',
      'sug.expensive.body': '<strong>{monthly}/mo</strong> = {yearly}/year. When was the last time you used it?',
      'sug.trial.title': '{name} trial ends {when}',
      'sug.trial.body': 'Will auto-renew at <strong>{price}</strong>. Cancel now if you don\\'t want it.',
      'sug.old.title': '{name} has been on your list for 6+ months',
      'sug.old.body': "Still actively using it? You've paid <strong>{paid}</strong> so far for it.",
      'sug.zombie.title': '{name} is a zombie',
      'sug.zombie.body': "You haven't used this for over 30 days. Cancel it to save <strong>{monthly}/mo</strong>.",
      // Time
      'time.today': 'today',
      'time.tomorrow': 'tomorrow',
      'time.inDays': 'in {n} days',
      'time.dueToday': 'Due today',
      'time.dueTomorrow': 'Tomorrow',
      'time.dueIn': 'In {n}d',
      'time.trialEnds': 'Trial ends {when}',
      // Menu
      'menu.settings': 'Settings',
      'menu.pro': 'Upgrade to Pro',
      'menu.proSub': 'Email reminders, sync, year-end report',
      'menu.proOn': "You're on Pro",
      'menu.proOnSub': 'Manage your license',
      'menu.import': 'Bulk import',
      'menu.importSub': 'Paste a list or upload CSV',
      'menu.export': 'Export CSV',
      'menu.exportSub': 'Download all your data',
      'menu.calendar': 'Calendar export',
      'menu.calendarSub': 'Renewal dates as an .ics file',
      'menu.yearend': 'Year-end report',
      'menu.yearendSub': 'See your spending wrap-up',
      'menu.currency': 'Currency',
      'menu.language': 'Language',
      'menu.share': 'Share leakd.app',
      'menu.shareSub': 'Help us grow',
      'menu.reset': 'Reset all data',
      'menu.resetSub': 'Wipe and start over',
      'menu.footer': 'leakd v1.2 · made for indie wallets',
      // Pro modal
      'pro.title': 'Leakd Pro',
      'pro.priceSub': 'or $39/year (save 35%)',
      'pro.f1': 'Email reminders before renewal',
      'pro.f2': 'Multi-device sync (encrypted)',
      'pro.f3': 'Year-end spending report',
      'pro.f4': 'Category budgets & alerts',
      'pro.f5': 'Priority email support',
      'pro.playNote': 'Purchases are tied to your Google Account.',
      'pro.buyMonthly': 'Upgrade to Pro Monthly',
      'pro.buyYearly': 'Upgrade to Pro Yearly',
      'pro.welcome': "You're on Pro",
      'pro.thanks': 'Thanks for supporting indie software. All premium features are unlocked.',
      'pro.activePlan': 'Active Plan',
      'pro.activated': 'Welcome to Pro!',
      'pro.verifying': 'Processing...',
      // Import
      'import.title': 'Bulk import',
      'import.blurb': "Paste one subscription per line. We'll try to detect the service and price automatically.",
      'import.uploadCSV': 'Upload CSV',
      'import.example': 'Try an example',
      'import.found': 'Found {count} subscriptions',
      'import.detected': 'detected',
      'import.nothingFound': 'Nothing detected — try one item per line, e.g. "Netflix 15.99"',
      'import.confirm': 'Import {count}',
      'import.imported': 'Imported {count} subscriptions',
      'import.placeholder': 'Netflix 15.99\\nSpotify 10.99\\nChatGPT 20\\nNotion 10/mo\\nAdobe yearly 599',
      // Share card
      'share.title': 'Your leak card',
      'share.note': 'Posts well on Twitter, Instagram, and Reddit. Tag <strong>@leakdapp</strong> if you share!',
      'share.download': 'Download',
      'share.now': 'Share',
      'share.saved': 'Saved',
      'share.savedDevice': 'Saved to your device',
      'share.addFirst': 'Add some subscriptions first',
      'share.tagline': 'Where my money leaks',
      'share.monthlySpend': 'Monthly spend',
      'share.perYear': '= {amount} per year',
      'share.topLeaks': 'TOP LEAKS',
      'share.trackedCount': '{count} subscriptions tracked',
      'share.features': 'Free · No account · Private',
      'share.noSubs': '(no subscriptions tracked yet)',
      'share.tag0': 'No leaks — yet',
      'share.tag1': 'Barely a drip',
      'share.tag2': 'A small leak',
      'share.tag3': 'Real money',
      'share.tag4': 'A serious leak',
      'share.tag5': 'Wake-up call',
      'share.tag6': 'How are you still standing',
      // Year-end report
      'yearend.title': 'Your {year} wrap-up',
      'yearend.totalPaid': "You paid",
      'yearend.totalPaidSub': 'across all subscriptions',
      'yearend.topName': 'Your biggest leak',
      'yearend.topBody': '{name} alone cost you {amount}.',
      'yearend.subCount': '{count} subscriptions tracked',
      'yearend.busiestCat': 'Most spent on',
      'yearend.share': 'Share',
      'yearend.close': 'Close',
      'yearend.emptyTitle': 'Nothing to wrap up yet',
      'yearend.emptySub': 'Add some subscriptions and check back here later in the year.',
      // Calendar
      'cal.exported': 'Calendar exported',
      'cal.noDates': 'No renewal dates to export yet',
      // Language
      'lang.choose': 'Choose language',
      // Onboarding
      'onb1.title': "Where's your money leaking?",
      'onb1.body': "Add the subscriptions you pay for. We'll show you the damage — and how to stop it.",
      'onb2.title': 'Stays on your device',
      'onb2.body': "No account, no cloud. Your subscription list never leaves your phone or laptop. Open the menu anytime to export or wipe everything.",
      'onb3.title': 'Get a heads-up',
      'onb3.body': "Allow notifications and we'll ping you before a free trial auto-renews. You can change this anytime.",
      'onb.skip': 'Maybe later',
      'onb.allow': 'Allow',
      // Toasts
      'toast.exported': 'Exported {n} subscriptions',
      'toast.nothing': 'Nothing to export',
      'toast.linkCopied': 'Link copied',
      // Reset
      'reset.confirm1': 'This wipes every subscription and setting on this device. Continue?',
      'reset.confirm2': 'Really? This cannot be undone.',
      // Search
      'search.placeholder': 'Search subscriptions…',
      'search.noResults': 'No matches',
      // Cancellation
      'btn.cancelSub': 'Cancel this subscription',
      // Paused
      'badge.paused': 'Paused',
      // Backup & restore
      'menu.backup': 'Backup & restore',
      'menu.backupSub': 'Save your data to a file or restore it',
      'backup.title': 'Backup & restore',
      'backup.blurb': 'Export everything (subscriptions, settings, notifications, Pro key) as a single file. Use it to move between devices or keep a safety copy.',
      'backup.exportTitle': 'Download backup',
      'backup.exportSub': 'A small JSON file you can keep anywhere',
      'backup.importTitle': 'Restore from backup',
      'backup.importSub': 'Replace current data with a backup file',
      'backup.exportBtn': 'Download',
      'backup.importBtn': 'Choose file',
      'backup.confirmImport': 'This replaces every subscription on this device with the backup. Continue?',
      'backup.imported': 'Backup restored',
      'backup.invalidFile': "That doesn't look like a Leakd backup file.",
      'backup.exported': 'Backup downloaded',
      // Category budgets
      'menu.budgets': 'Category budgets',
      'menu.budgetsSub': 'Set monthly limits per category',
      'budgets.title': 'Category budgets',
      'budgets.blurb': 'Set a monthly limit for each category. We\\'ll show your progress and warn when you go over.',
      'budgets.proLock': 'Budgets are a Pro feature. Upgrade to unlock.',
      'budgets.empty': 'No budgets set yet. Tap a category below to set one.',
      'budgets.over': 'Over budget',
      'budgets.warn': 'Almost at the limit',
      'budgets.spent': '{spent} of {limit}',
      'budgets.setLimit': 'Set monthly limit',
      'toast.budgetSaved': 'Budget saved',
      'toast.budgetCleared': 'Budget cleared',
      // History sparkline
      'sparkline.30days': 'Last 30 days',
      // Notes
      'field.notes': 'Notes',
      'field.notesPh': "What's worth remembering about this sub?",
      // Tracked since
      'tracked.since': 'Tracked since {when}',
      'tracked.months': '{n} months',
      'tracked.years': '{n} years',
      'tracked.both': '{years}y {months}mo',
      // Income & ratio
      'menu.income': 'Income & ratio',
      'menu.incomeSub': 'See what % of your income goes to subs',
      'income.title': 'Monthly income',
      'income.blurb': 'Optional. We use it to show what share of your income goes to subscriptions. Stored on this device only.',
      'income.label': 'Net monthly income',
      'income.placeholder': '3000',
      'income.clear': 'Clear',
      'income.empty': 'Set your income to see the ratio.',
      'income.ratio.label': 'of your income',
      'income.ratio.fine': 'Healthy',
      'income.ratio.high': 'Getting heavy',
      'income.ratio.crisis': 'Subscription spiral 😬',
      'toast.incomeSaved': 'Income saved',
      // Donut + suggestion list
      'autocomplete.label': 'Suggestions',
      'donut.title': 'Spending share',
      // Cancelled subs registry
      'btn.cancelMark': 'Mark as cancelled',
      'btn.deleteForever': 'Delete forever',
      'confirm.markCancelled': 'Mark this subscription as cancelled? It moves to your cancelled list and stops counting in totals.',
      'cancelled.title': 'Cancelled subscriptions',
      'cancelled.empty': "No cancellations yet. When you kill a sub, we'll celebrate it here.",
      'cancelled.savingsLabel': 'Saved every month',
      'cancelled.thisYear': 'cancelled in {year}',
      'cancelled.restoreBtn': 'Restore',
      'cancelled.purgeBtn': 'Delete forever',
      'cancelled.confirmRestore': 'Restore this subscription back to your active list?',
      'cancelled.confirmPurge': 'Permanently delete this cancellation record? Stats will lose this win.',
      'menu.cancelled': 'Cancelled subscriptions',
      'menu.cancelledSub': 'See what you killed and how much you saved',
      'toast.subCancelled': 'Subscription cancelled',
      'toast.subRestored': 'Subscription restored',
      // Forecast widget
      'forecast.title': 'Next {n} days',
      'forecast.total': '{total} across {count} renewals',
      'forecast.none': 'No renewals coming up. Breathe easy.',
      // Worth-it rating
      'field.rating': 'Worth it?',
      'field.ratingPh': 'Tap stars',
      'insights.lowestRated': 'Lowest-rated subscriptions',
      'insights.lowestRatedSub': 'Easy cancellation candidates',
      // System theme
      'theme.light': 'Light',
      'theme.dark': 'Dark',
      'theme.auto': 'Auto (system)',
      'menu.theme': 'Theme',
      'menu.themeSub': 'Light, dark, or follow your system',
      // Lifetime cost & investment alternative
      'lifetime.title': 'Lifetime cost',
      'lifetime.paidSoFar': "You've paid",
      'lifetime.since': 'since {date}',
      'lifetime.next5y': 'Next 5 years',
      'lifetime.next10y': 'Next 10 years',
      'lifetime.investTitle': 'If you invested instead',
      'lifetime.investNote': 'At 7% annual return (S&P 500 long-term avg)',
      'lifetime.invest5y': '5 years invested',
      'lifetime.invest10y': '10 years invested',
      // Family share
      'field.shared': 'Shared with',
      'field.sharedPh': '1',
      'field.sharedNote': 'Total cost stays the same — we just show your share too',
      'share.yourShare': 'Your share: {amount}',
      // Cancellation playbooks
      'playbook.title': 'How to cancel',
      'playbook.difficulty': 'Difficulty',
      'playbook.time': '~{n} min',
      'playbook.diffEasy': 'Easy',
      'playbook.diffMedium': 'Medium',
      'playbook.diffHard': 'Hard',
      'playbook.steps': 'Steps',
      // Calendar view
      'calendar.title': 'Renewal calendar',
      'calendar.prev': 'Previous month',
      'calendar.next': 'Next month',
      'calendar.thisMonth': '{count} renewals · {total} this month',
      'calendar.empty': 'No renewals this month',
      'calendar.dayDetail': '{date} · {count} renewal',
      'calendar.dayDetailPlural': '{date} · {count} renewals',
      // Aggregate lifetime
      'insights.lifetimeTitle': 'Lifetime paid (all subs)',
      'menu.privacy': 'Privacy policy',
      'menu.privacySub': 'Read what we store (spoiler: nothing)',
      'menu.terms': 'Terms of service',
      'menu.termsSub': 'The boring fine print',
      'menu.bank': 'Import bank statement',
      'menu.bankSub': 'Auto-detect subs from Revolut, Wise, Chase, etc.',
      'bank.title': 'Import bank statement',
      'bank.blurb': 'Upload a CSV from your bank — Revolut, Wise, N26, PayPal, Chase, Amex. We parse it locally and detect recurring charges. Nothing leaves your device.',
      'bank.upload': 'Choose CSV file',
      'bank.formatDetected': 'Detected: {name}',
      'bank.foundRecurring': 'Found {count} recurring charges',
      'bank.noRecurring': 'No recurring charges detected. Try a 3+ month statement.',
      'bank.confidence': '{n} payments · {confidence}% confidence',
      'bank.lastSeen': 'Last seen {when}',
      'bank.importSelected': 'Import {count}',
      'bank.errorColumns': "Couldn't find date/description/amount columns in this file.",
      'bank.parsed': 'Imported {count} subscriptions from statement',
      'menu.goal': 'Savings goal',
      'menu.goalSub': 'Set a target — we celebrate every milestone',
      'goal.title': 'Savings goal',
      'goal.nameLabel': 'What are you saving for?',
      'goal.estimate': 'Cancel {count} low-rated subs to save <strong>{savings}/mo</strong> and hit your goal in <strong>{months} months</strong>!',
      'goal.progressShort': 'Goal progress: {saved} ({pct}%)',
      'menu.activity': 'Activity log',
      'menu.activitySub': 'See every change you made',
      'activity.title': 'Activity log',
      'activity.empty': 'No activity yet. Add a subscription to start your journey.',
      'activity.added': 'Added {name}',
      'activity.edited': 'Edited {name}',
      'activity.cancelled': 'Cancelled {name}',
      'activity.paused': 'Paused {name}',
      'activity.resumed': 'Resumed {name}',
      'activity.restored': 'Restored {name}',
      'activity.deleted': 'Deleted {name}',
      'activity.imported': 'Imported {n} subscriptions',
      'personality.title': 'Your subscription personality',
      'personality.quietCutter': 'The Quiet Cutter',
      'personality.quietCutterTag': "You've killed multiple subs this year — quietly winning",
      'personality.bundleMaster': 'Bundle Master',
      'personality.bundleMasterTag': 'You know how to stack savings',
      'personality.streamingJunkie': 'Streaming Junkie',
      'personality.streamingJunkieTag': 'Three or more entertainment subs — you love your shows',
      'personality.aiHoarder': 'AI Hoarder',
      'personality.aiHoarderTag': 'Collecting AI tools faster than they ship updates',
      'personality.productivityStack': 'The Productivity Stack',
      'personality.productivityStackTag': 'Five or more work tools — power user energy',
      'personality.musicSnob': 'Music Snob',
      'personality.musicSnobTag': 'Multiple music services — discerning ear',
      'personality.spiraler': 'Subscription Spiraler',
      'personality.spiralerTag': 'Ten or more active subs. Maybe time to audit?',
      'personality.minimalist': 'The Healthy Minimalist',
      'personality.minimalistTag': 'Few subs, all rated high. Inspiration.',
      'personality.forgotten': 'The Forgotten',
      'personality.forgottenTag': 'You have subs older than a year you never rate',
      'personality.starting': 'Just Getting Started',
      'personality.startingTag': 'Welcome — every leak begins with one drip',
      'bench.title': 'How you compare',
      'bench.expected': 'Average for {count} subs: {expected}',
      'bench.percentile': 'Top {pct}% of trackers',
      'bench.lower': 'below average',
      'bench.average': 'on average',
      'bench.higher': 'above average',
      'bench.muchHigher': 'way above',
      'menu.whatif': 'What-if calculator',
      'menu.whatifSub': 'Pick subs to cancel — see savings live',
      'whatif.title': 'What-if calculator',
      'whatif.blurb': 'Tap subscriptions to mark them as cancelled in this scenario. We show what you would save without changing your real data.',
      'whatif.empty': 'No active subscriptions to simulate.',
      'whatif.suggestBtn': 'Suggest top picks',
      'whatif.clearBtn': 'Clear all',
      'whatif.summarySelected': '{n} selected',
      'whatif.summarySavings': '{monthly}/mo · {yearly}/yr',
      'whatif.investedNote': 'Invested at 7%: {y5} in 5 years, {y10} in 10',
      'home.notesLabel': 'Notes',
      'streak.days': 'day streak',
      'streak.msg': 'Did you resist a new subscription today?',
      'streak.btn': 'I stayed clean!',
      'streak.done': 'Stayed clean today! ✨',
      'streak.msgDone': 'Great job! See you tomorrow to keep the screen clean.',
      'toast.streakUpdated': 'Streak updated! 🔥',
      'field.tags': 'Tags',
      'field.tagsPh': 'work, family, considering, …',
      'field.tagsNote': 'Free-form labels. Separate with commas.',
      'home.tagFilter': 'Filter by tag',
      'home.allTags': 'All tags',
      'lifetime.inflationTitle': 'If prices keep rising',
      'lifetime.inflationNote': 'Most subs raise prices 3-7%/year. We project 5% — typical for SaaS.',
      'lifetime.inflated10y': '10 years at +5%/yr',
      'menu.compare': 'Compare side-by-side',
      'menu.compareSub': 'Pick 2 or 3 to compare',
      'compare.title': 'Compare side-by-side',
      'compare.blurb': 'Pick 2 or 3 subscriptions. We line them up so you can see which one to cut.',
      'compare.pickPrompt': 'Tap to select up to 3 subscriptions',
      'compare.minPrompt': 'Pick at least 2 subscriptions to compare',
      'compare.monthly': 'Monthly',
      'compare.yearly': 'Yearly',
      'compare.lifetime': 'Lifetime paid',
      'compare.rating': 'Rating',
      'compare.cancelDiff': 'Cancel difficulty',
      'compare.alternatives': 'Alternatives',
      'compare.notRated': '— not rated',
      'compare.diff.easy': 'Easy',
      'compare.diff.medium': 'Medium',
      'compare.diff.hard': 'Hard',
      'compare.diff.unknown': 'Unknown',
      'compare.altCountN': '{n} options',
      'compare.minutesAbbr': '{n} min',
    },`;

// Find the start of STRINGS = {
const stringsStartIndex = content.indexOf('const STRINGS = {');
// Find the first en: { after that
const enStartIndex = content.indexOf('en: {', stringsStartIndex);
// Find the hu: { after en: {
const huStartIndex = content.indexOf('hu: {', enStartIndex);

if (enStartIndex !== -1 && huStartIndex !== -1) {
    content = content.substring(0, enStartIndex) + cleanEnStrings + content.substring(huStartIndex);
    fs.writeFileSync(path, content, 'utf8');
    console.log('English block scrubbed and reset to clean version!');
} else {
    console.error('Could not find en: { or hu: { blocks!');
}
